"""Mechanic B -- workflow execution analyzer.

After every task completes, Mechanic B inspects the execution data (and
LangSmith traces when available) for the run and produces:
  - Quality scores (task completion, efficiency, cost, SOP adherence, error rate)
  - Improvement proposals (prompt tweaks, tool changes, SOP updates)
  - A human-readable summary posted to the admin approvals channel

Proposals require explicit human approval before they take effect. Approved
proposals are committed to git; rejected proposals are logged and discarded.
"""

from __future__ import annotations

import logging
from enum import Enum
from pathlib import Path
from typing import Any

import yaml
from langgraph.graph import END, StateGraph
from pydantic import BaseModel, Field

from ..nodes.llm import call_claude, call_claude_structured

logger = logging.getLogger(__name__)

_PROJECT_ROOT = Path(__file__).resolve().parent.parent.parent


# ---------------------------------------------------------------------------
# State schema
# ---------------------------------------------------------------------------

class ProposalStatus(str, Enum):
    PENDING = "pending"
    APPROVED = "approved"
    REJECTED = "rejected"


class ImprovementProposal(BaseModel):
    """A single improvement proposal generated by Mechanic B."""
    id: str
    category: str = ""          # e.g. "prompt", "tool", "sop", "workflow"
    description: str = ""
    diff: str = ""              # Git-style diff of the proposed change
    confidence: float = 0.0     # 0.0 -- 1.0
    status: ProposalStatus = ProposalStatus.PENDING


class MechanicBState(BaseModel):
    """Typed state for the Mechanic B analysis graph."""

    # -- Input --
    run_id: str = ""
    trace_id: str = ""
    thread_id: str = ""
    workspace_id: str = ""

    # -- Trace data --
    trace_data: dict[str, Any] = Field(default_factory=dict)
    node_timings: dict[str, float] = Field(default_factory=dict)
    token_usage: dict[str, int] = Field(default_factory=dict)
    tool_calls: list[dict[str, Any]] = Field(default_factory=list)

    # -- Analysis --
    quality_scores: dict[str, float] = Field(default_factory=dict)
    proposals: list[ImprovementProposal] = Field(default_factory=list)
    summary: str = ""

    # -- Output --
    report: dict[str, Any] = Field(default_factory=dict)
    errors: list[str] = Field(default_factory=list)


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _load_evaluation_criteria() -> dict[str, Any]:
    """Load Mechanic B evaluation criteria from the platform config."""
    criteria_path = _PROJECT_ROOT / "platform" / "mechanics" / "evaluation-criteria.yaml"
    try:
        raw = yaml.safe_load(criteria_path.read_text(encoding="utf-8"))
        return raw.get("mechanic_b", {})
    except (FileNotFoundError, yaml.YAMLError, OSError) as exc:
        logger.warning("Could not load evaluation criteria: %s", exc)
        return {}


def _load_mechanic_b_prompt() -> str:
    """Load the Mechanic B system prompt from platform config."""
    prompt_path = _PROJECT_ROOT / "platform" / "mechanics" / "mechanic-b-prompt.md"
    try:
        return prompt_path.read_text(encoding="utf-8")
    except (FileNotFoundError, OSError) as exc:
        logger.warning("Could not load Mechanic B prompt: %s", exc)
        return (
            "You are Mechanic B, a workflow execution analyzer. "
            "Analyze execution data and propose improvements."
        )


# ---------------------------------------------------------------------------
# Node implementations
# ---------------------------------------------------------------------------

def fetch_traces(state: MechanicBState) -> dict[str, Any]:
    """Retrieve trace data for the completed run.

    Currently collects execution data passed through the state (from the main
    graph). When LangSmith is connected, this will also fetch the full trace
    tree via the LangSmith SDK.
    """
    errors: list[str] = list(state.errors)
    trace_data = dict(state.trace_data)

    # Extract timing and token data from the execution results if available
    node_timings: dict[str, float] = {}
    token_usage: dict[str, int] = {"input_tokens": 0, "output_tokens": 0}
    tool_calls: list[dict[str, Any]] = []

    # Count steps and their statuses from the passed-in trace data
    execution_results = trace_data.get("execution_results", {})
    plan = trace_data.get("plan", [])

    for step in plan:
        step_id = step.get("id", "unknown")
        result = execution_results.get(step_id, {})
        # Placeholder timing (real timing would come from LangSmith)
        node_timings[step_id] = 0.0

    trace_data["step_count"] = len(plan)
    trace_data["completed_count"] = sum(
        1 for r in execution_results.values()
        if isinstance(r, dict) and r.get("status") == "completed"
    )
    trace_data["error_count"] = sum(
        1 for r in execution_results.values()
        if isinstance(r, dict) and r.get("status") == "error"
    )

    # TODO: When LangSmith is connected, fetch real traces:
    # from langsmith import Client
    # ls_client = Client()
    # run = ls_client.read_run(state.run_id)
    # ... extract timings, token counts, tool calls

    return {
        "trace_data": trace_data,
        "node_timings": node_timings,
        "token_usage": token_usage,
        "tool_calls": tool_calls,
        "errors": errors,
    }


def analyze_quality(state: MechanicBState) -> dict[str, Any]:
    """Score the execution across quality dimensions using Claude as a judge.

    Dimensions (from evaluation-criteria.yaml):
      - task_completion: Did the workflow produce the expected deliverables?
      - efficiency: Token usage and time relative to task complexity
      - sop_adherence: Did the workflow follow the defined SOP steps?
      - error_rate: Number of errors or retries during execution
      - cost: Total cost relative to task value
    """
    errors: list[str] = list(state.errors)
    criteria = _load_evaluation_criteria()
    criteria_list = criteria.get("criteria", [])

    trace_data = state.trace_data
    task = trace_data.get("task", "Unknown task")
    deliverables = trace_data.get("deliverables", [])
    plan = trace_data.get("plan", [])
    matched_sop = trace_data.get("matched_sop")
    step_count = trace_data.get("step_count", 0)
    completed_count = trace_data.get("completed_count", 0)
    error_count = trace_data.get("error_count", 0)

    # Build a summary for Claude to evaluate
    deliverable_summaries = []
    for d in deliverables:
        content = d.get("content", "")
        preview = content[:300] + "..." if len(content) > 300 else content
        deliverable_summaries.append(f"- [{d.get('step_id', '?')}]: {preview}")

    evaluation_prompt = f"""Evaluate this workflow execution on the following quality dimensions.

## Task
{task}

## Execution Summary
- Total steps planned: {step_count}
- Steps completed: {completed_count}
- Steps with errors: {error_count}
- SOP used: {matched_sop or 'None (ad-hoc planning)'}

## Deliverables Produced
{chr(10).join(deliverable_summaries) if deliverable_summaries else 'None'}

## Evaluation Criteria
Score each dimension from 0.0 to 1.0:

{chr(10).join(f"- {c['name']} (weight {c['weight']}): {c['description']}" for c in criteria_list) if criteria_list else '''- task_completion: Did the workflow produce expected deliverables?
- efficiency: Were resources used well relative to task complexity?
- sop_adherence: Did the workflow follow the defined process?
- error_rate: How many errors or issues occurred?
- cost: Was the cost reasonable for the task?'''}

Return a JSON object with a key "scores" mapping each dimension name to a float between 0.0 and 1.0.
Also include a "reasoning" key with a brief explanation for each score."""

    scores_schema = {
        "type": "object",
        "properties": {
            "scores": {
                "type": "object",
                "additionalProperties": {"type": "number"},
            },
            "reasoning": {
                "type": "object",
                "additionalProperties": {"type": "string"},
            },
        },
        "required": ["scores", "reasoning"],
    }

    try:
        result = call_claude_structured(
            prompt=evaluation_prompt,
            system=_load_mechanic_b_prompt(),
            response_schema=scores_schema,
            model="claude-sonnet-4-6",
            temperature=0.0,
        )
        quality_scores = result.get("scores", {})
        # Store reasoning in trace_data for the report
        trace_data_with_reasoning = {
            **state.trace_data,
            "quality_reasoning": result.get("reasoning", {}),
        }
    except Exception as exc:
        logger.error("Quality analysis failed: %s", exc)
        errors.append(f"Quality analysis error: {exc}")
        quality_scores = {
            "task_completion": completed_count / max(step_count, 1),
            "efficiency": 0.5,
            "sop_adherence": 1.0 if matched_sop else 0.5,
            "error_rate": 1.0 - (error_count / max(step_count, 1)),
            "cost": 0.5,
        }
        trace_data_with_reasoning = state.trace_data

    return {
        "quality_scores": quality_scores,
        "trace_data": trace_data_with_reasoning,
        "errors": errors,
    }


def generate_proposals(state: MechanicBState) -> dict[str, Any]:
    """Generate improvement proposals based on the analysis.

    Uses Claude to identify concrete improvements and produce git-style diffs.
    Only proposes changes when there is clear evidence of improvement potential.
    Respects the "default is no change" philosophy.
    """
    errors: list[str] = list(state.errors)
    proposals: list[ImprovementProposal] = []

    # Only generate proposals if there are quality issues
    low_scores = {
        name: score
        for name, score in state.quality_scores.items()
        if score < 0.7
    }

    if not low_scores:
        logger.info("All quality scores >= 0.7, no proposals needed.")
        return {"proposals": [], "errors": errors}

    trace_data = state.trace_data
    reasoning = trace_data.get("quality_reasoning", {})

    proposal_prompt = f"""Based on this workflow execution analysis, propose specific improvements.

## Quality Scores (below threshold)
{chr(10).join(f"- {name}: {score:.2f} — {reasoning.get(name, 'No reasoning available')}" for name, score in low_scores.items())}

## Execution Details
- Task: {trace_data.get('task', 'Unknown')}
- SOP: {trace_data.get('matched_sop', 'None')}
- Steps: {trace_data.get('step_count', 0)} planned, {trace_data.get('completed_count', 0)} completed, {trace_data.get('error_count', 0)} errors

## Rules
1. Only propose changes with CLEAR EVIDENCE of improvement
2. Each proposal must include a git-style diff showing the exact change
3. Assign a confidence score (0.0-1.0) — only include proposals with confidence >= 0.6
4. Categories: "prompt", "tool", "sop", "workflow"
5. If you cannot articulate WHY with evidence, do NOT propose the change

Return a JSON object with a key "proposals" containing an array of proposal objects, each with:
- id: short kebab-case identifier
- category: one of prompt/tool/sop/workflow
- description: what changes and why, with evidence
- diff: git-style unified diff of the proposed change
- confidence: float 0.0-1.0"""

    proposals_schema = {
        "type": "object",
        "properties": {
            "proposals": {
                "type": "array",
                "items": {
                    "type": "object",
                    "properties": {
                        "id": {"type": "string"},
                        "category": {"type": "string"},
                        "description": {"type": "string"},
                        "diff": {"type": "string"},
                        "confidence": {"type": "number"},
                    },
                    "required": ["id", "category", "description", "confidence"],
                },
            },
        },
        "required": ["proposals"],
    }

    try:
        result = call_claude_structured(
            prompt=proposal_prompt,
            system=_load_mechanic_b_prompt(),
            response_schema=proposals_schema,
            model="claude-opus-4-6",
            temperature=0.0,
        )
        for p in result.get("proposals", []):
            if p.get("confidence", 0) >= 0.6:
                proposals.append(ImprovementProposal(
                    id=p["id"],
                    category=p.get("category", "workflow"),
                    description=p.get("description", ""),
                    diff=p.get("diff", ""),
                    confidence=p.get("confidence", 0.0),
                ))
    except Exception as exc:
        logger.error("Proposal generation failed: %s", exc)
        errors.append(f"Proposal generation error: {exc}")

    return {"proposals": proposals, "errors": errors}


def compile_report(state: MechanicBState) -> dict[str, Any]:
    """Package scores, proposals, and a human-readable summary into a report."""
    errors: list[str] = list(state.errors)

    # Generate a human-readable summary
    trace_data = state.trace_data
    reasoning = trace_data.get("quality_reasoning", {})

    # Calculate weighted overall score
    criteria = _load_evaluation_criteria()
    criteria_weights = {
        c["name"]: c["weight"]
        for c in criteria.get("criteria", [])
    }
    # Use default weights if criteria not loaded
    if not criteria_weights:
        criteria_weights = {
            "task_completion": 0.3,
            "efficiency": 0.2,
            "sop_adherence": 0.2,
            "error_rate": 0.15,
            "cost": 0.15,
        }

    overall_score = 0.0
    total_weight = 0.0
    for name, score in state.quality_scores.items():
        weight = criteria_weights.get(name, 0.1)
        overall_score += score * weight
        total_weight += weight
    if total_weight > 0:
        overall_score /= total_weight

    # Build summary sections
    summary_parts = [
        f"## Mechanic B Analysis Report",
        f"**Run ID:** {state.run_id}",
        f"**Overall Score:** {overall_score:.2f}/1.00",
        "",
        "### Quality Scores",
    ]
    for name, score in sorted(state.quality_scores.items()):
        emoji_indicator = "PASS" if score >= 0.7 else "NEEDS IMPROVEMENT"
        summary_parts.append(f"- **{name}:** {score:.2f} [{emoji_indicator}]")
        if name in reasoning:
            summary_parts.append(f"  - {reasoning[name]}")

    if state.proposals:
        summary_parts.append("")
        summary_parts.append(f"### Improvement Proposals ({len(state.proposals)})")
        for p in state.proposals:
            summary_parts.append(
                f"- **[{p.category}] {p.id}** (confidence: {p.confidence:.2f})"
            )
            summary_parts.append(f"  {p.description}")
            if p.diff:
                summary_parts.append(f"  ```diff\n  {p.diff}\n  ```")
    else:
        summary_parts.append("")
        summary_parts.append("### No improvement proposals generated.")
        summary_parts.append("All quality dimensions are within acceptable thresholds.")

    summary = "\n".join(summary_parts)

    report = {
        "run_id": state.run_id,
        "workspace_id": state.workspace_id,
        "overall_score": overall_score,
        "quality_scores": state.quality_scores,
        "quality_reasoning": reasoning,
        "proposals": [p.model_dump() for p in state.proposals],
        "summary": summary,
        "error_count": len(state.errors),
    }

    return {
        "summary": summary,
        "report": report,
        "errors": errors,
    }


# ---------------------------------------------------------------------------
# Graph assembly
# ---------------------------------------------------------------------------

def build_graph() -> StateGraph:
    """Construct and compile the Mechanic B analysis graph."""

    builder = StateGraph(MechanicBState)

    builder.add_node("fetch_traces", fetch_traces)
    builder.add_node("analyze_quality", analyze_quality)
    builder.add_node("generate_proposals", generate_proposals)
    builder.add_node("compile_report", compile_report)

    builder.set_entry_point("fetch_traces")

    builder.add_edge("fetch_traces", "analyze_quality")
    builder.add_edge("analyze_quality", "generate_proposals")
    builder.add_edge("generate_proposals", "compile_report")
    builder.add_edge("compile_report", END)

    return builder


graph = build_graph().compile()
